### ISSUE TITLE
Multi resolve username -> full name

### ISSUE THREAD

**Issue by bastihav** [upb-uc4/lagom-core#179]
**Is your feature request related to a problem? Please describe.**
Currently, we want to show the full lecturer name for each course. This means that for every course, we need to resolve the username to a lecturer object to show the name, which means we need an API call for each course, which introduces a lot of overhead due to RTT.

**Describe the solution you'd like**
- You implement a new endpoint that allows us to fetch a list of users, if we provide a list of usernames. I am not sure how to model this, as GET usually does not have any body, so we would probably need something like /lecturers?name=lecturer&name=lecturer2&name=lecturer3 ...

**Describe alternatives you've considered**
There are a few options:
- We could just fetch all lecturers using the already implemented API endpoints and resolve the names ourselves, which would introduce overhead as we fetch ALL lecturers, instead of the ones we are interested in.
- We add the full lecturer name to the course object (duplication of data)

**Comment by david-buderus** [comment]
You could send the usernames in the header but I don't know if this is forbidden in the standard.
