### ISSUE TITLE
Whenever an internal server error is thrown, show info in dev mode, but not in prod

### ISSUE THREAD

**Issue by dhelmert** [upb-uc4/lagom-core#207]
Currently, we sometimes check for errors, and throw an internal server error without info if an error occurred. Change it in a way, that in dev mode information of the exception is printed, while in production it should not be.
=>Implement the check in ExceptionSerializer

**Comment by david-buderus** [comment]
In the CustomExceptionSerializer in line 17 it just needs a new case with this guard `if environment.mode == Mode.Dev`.
In addition the internal server error needs to be used in a DetailedError, to have information that can be send.

But this needs first the change to Enums to be implemented and merged.
