### ISSUE TITLE
Remove Basic Authentication

### ISSUE THREAD

**Issue by david-buderus** [upb-uc4/lagom-core#260]
**Is your feature request related to a problem? Please describe.**
Basic is not a good authentication method even with HTTPS.
Besides it blocks a good solution for #211.

**Describe the solution you'd like**
We could use Digest Authentication.

**Comment by lrschaef** [comment]
I don't think using digest would improve the security of our initial auth process. Because digest uses md5, it may even weaken our password security.

**Comment by ldklenner** [comment]
The original specification used MD5, updated version support secure hash functions like SHA-256, described in (RFC7616)[https://tools.ietf.org/html/rfc7616]. Basically, every MD5 call is replaced with a SHA-256 call.

**Comment by ldklenner** [comment]
Keep also in mind that Digest Authentication involves at least two communication rounds. The client makes a login request which the server answers among others with a `nonce`. The server has to store the `nonce`. The client then computes the digest and sends it to the server which recomputes the digest and checks for equality. If everything is sound the server will answers with login credentials (tokens).

**Comment by lrschaef** [comment]
> 
> 
> The original specification used MD5, updated version support secure hash functions like SHA-256, described in [RFC7616](https://tools.ietf.org/html/rfc7616). Basically, every MD5 call is replaced with a SHA-256 call.

In that case digest might be an option. My question would be, what we gain from using digest instead of just basic with https and if the effort is worth it. It may very well be worth it, but more research is necessary for that.

**Comment by ldklenner** [comment]
Yes, we can use Digest and HTTPS. The benefit would be that the client does not send the plaintext password to the server. However I am not sure if the effort is worth it. Implementing Digest Authentication is more complex and multiple RFCs have to be considered. There are also some inconveniences I am not really sure about. Simplified the authentication revolves around hash "digested" secrets:

```
HA1 = H(username:realm:password)
response = MD5(HA1:nonce)
```

The server has to store either the plaintext password or the secret `HA1`. If the `HA1` secret is stored it basically becomes a plaintext secret. Currently we do not store a plaintext secret, we store a salted hash of the password. This would not be possible as we need to recompute the `response` with the corresponding `nonce`. To resolve this problem more sophisticated protocols are needed, which are hinted [here](https://security.stackexchange.com/questions/38845/how-can-salted-hashed-password-storage-be-combined-with-a-plaintext-nonce-and).

**Comment by bastihav** [comment]
Any updates on this? Do we want to implement it, or is basic + https "good enough"? Do we need another meeting for this in the future? @david-buderus @ldklenner @lrschaef

**Comment by david-buderus** [comment]
We could talk about this on a Monday Meeting with @bhermann
