### ISSUE TITLE
Gzipping

### ISSUE THREAD

**Issue by bastihav** [upb-uc4/lagom-core#271]
**Is your feature request related to a problem? Please describe.**
Our tests fail because requests and responses take too long. Also, users like fast websites.

**Describe the solution you'd like**
Add gzip compression to all responses for all services. Also, add gzip compression for requests

**Describe alternatives you've considered**
none

**Additional context**
To allow end users to gzip responses, you need to add a specific header to the options call I think.
We might need to change the http version in the webserver's nginx conf to http1.2 or higher, to enable gzip.

**Comment by david-buderus** [comment]
Play Framework has support for this feature.
