### ISSUE TITLE
Duplicate MatriculationID not rejected

### ISSUE THREAD

**Issue by tobias-wiese** [upb-uc4/lagom-core#292]
**Describe the bug**
When creating a student account with matnr "1234567", there is already matriculation data given. This happens if you add a student with a matnr that **was** in use and has matriculation data (on the chain). Conflicts with matnr currently in use result in an error as it should be.

**Expected behavior**
Should get an error, that the matnr was already been used (there is data for that ID)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/63233799/93889942-1bf7e880-fcea-11ea-8467-683f40df9d98.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser FF

**Additional context**
Tested against experimental deployment

**Comment by dhelmert** [comment]
This Bug can be fixed once we implement the feature that users cannot be completely deleted, but rather flagged as deleted

**Comment by lrschaef** [comment]
We now use the enrollmentID instead of the matriculation ID for storing matriculation data, therefore this bug can no longer occur.
