### ISSUE TITLE
Update MatriculationService According to new MatriculationAPI

### ISSUE THREAD

**Issue by NikoBergemann** [upb-uc4/lagom-core#293]
**Is your feature request related to a problem? Please describe.**
Current MatriuclationData is not sufficiently pseudonymized, so we will adjust what data to store on the chain.

**Describe the solution you'd like**
Deferred to API
- Remove personal info
- add enrollment.id

**Comment by dhelmert** [comment]
For this, we also need to add the governmentId to User object ( and update validation, toPublic, etc.)

**Comment by dhelmert** [comment]
As we will not use a hash of the governmentId as the pseudonym, but rather a random String, this issue can be closed
