### ISSUE TITLE
Add min size to gzip

### ISSUE THREAD

**Issue by bastihav** [upb-uc4/lagom-core#307]
**Describe the bug**
{"versionNumber":"v0.8.2"} (26 Bytes) is compressed to H4sIAAAAAAAA/6tWKkstKs7Mz/MrzU1KLVKyUioz0LPQM1KqBQCFk8npGgAAAA== (46 Bytes), which almost doubles the size. We should add a minimum size for gzip. A value between 150 Bytes and 1000 Bytes is recommended.

**Comment by david-buderus** [comment]
We need to set something like
```conf
play.filters.gzip.threshold = 500
```
in our application.conf
