### ISSUE TITLE
Register User in HLF

### ISSUE THREAD

**Issue by ldklenner** [upb-uc4/lagom-core#312]
When a user is created in Lagom it needs to be registered to Hyperledger

- [ ] Adapt API to include GovermentID in UserObject
- [ ] Compute EnrollmentID from GovernmentID and store it (Currently its the hashed username)
- [x] Register User in HLF
- [x] Store EnrollmentSecret and UserObject

**Comment by lrschaef** [comment]
We will not use the gov ID, because we decided that the data should be anynomous. (UUID f.e. will be used)
