### ISSUE TITLE
Validation Timeout for course creation

### ISSUE THREAD

**Issue by bastihav** [upb-uc4/lagom-core#409]
**Describe the bug**
Validation timeout when trying to create a course with multiple moduleIds.

**To Reproduce**
```
{
    "courseId": "",
    "moduleIds": [
        "M.1278.15686",
        "M.1275.01159"
    ],
    "courseName": "Analysis",
    "courseType": "Lecture",
    "startDate": "2020-12-08",
    "endDate": "2020-12-08",
    "ects": 10,
    "lecturerId": "lecturer",
    "maxParticipants": 100,
    "currentParticipants": 0,
    "courseLanguage": "German",
    "courseDescription": "Death of a lot of computer scientists"
  }
```
**Expected behavior**
Don't die

**Comment by ldklenner** [comment]
The validation timeout is to short for a database access fetching multiple modules . Database timeout was usually set to 5000 milliseconds.

**Comment by dhelmert** [comment]
Same issue for AddUser in UserService; the validationFuture depends on a getAllUsers call. This caused a timeout to occur at least once before, the new timeout is needed here as well
